CREATE TABLE tiendas (
    id_tienda NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    direccion VARCHAR2(200),
    ciudad VARCHAR2(100)
);


CREATE TABLE empleados (
    id_empleados NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_tienda NUMBER(10),
    nombre VARCHAR2(100),
    apellido VARCHAR2(100),
    puesto VARCHAR2(50),
    FOREIGN KEY (id_tienda) REFERENCES tiendas(id_tienda)
);


CREATE TABLE clientes (
    id_cliente NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    apellido VARCHAR2(100),
    email VARCHAR2(100),
    telefono VARCHAR2(15),
    direccion VARCHAR2(200)
);

CREATE TABLE categorias (
    id_categoria NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100)
);

CREATE TABLE productos (
    id_producto NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_categoria NUMBER(10),
    id_proveedor NUMBER(10), 
    nombre VARCHAR2(100),
    precio_producto NUMBER(10, 2),
    stock_producto NUMBER(10),
    descripcion VARCHAR2(200),
    FOREIGN KEY (id_categoria) REFERENCES categorias(id_categoria),
    FOREIGN KEY (id_proveedor) REFERENCES proveedor(id_proveedor)
);


CREATE TABLE inventarios (
    id_inventario NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_tienda NUMBER(10),
    total_productos NUMBER(10),
    FOREIGN KEY (id_tienda) REFERENCES tiendas(id_tienda)
);

CREATE TABLE ventas (
    id_ventas NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_cliente NUMBER(10),
    id_empleado NUMBER(10),
    id_producto NUMBER(10),
    id_tienda NUMBER(10),
    fecha DATE,
    cantidad NUMBER(10),
    total NUMBER(10, 2),
    FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente),
    FOREIGN KEY (id_empleado) REFERENCES empleados(id_empleados),
    FOREIGN KEY (id_producto) REFERENCES productos(id_producto),
    FOREIGN KEY (id_tienda) REFERENCES tiendas(id_tienda)
);


CREATE TABLE proveedor (
    id_proveedor NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    descripcion VARCHAR2(200),
    ciudad VARCHAR2(100),
    telefono VARCHAR2(15)
);


CREATE TABLE pedidos (
    id_pedido NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_proveedor NUMBER(10),
    id_tienda NUMBER(10),
    fecha_pedido DATE,
    total_unidades NUMBER(10), 
    id_productos NUMBER(10),
    FOREIGN KEY (id_proveedor) REFERENCES proveedor(id_proveedor),
    FOREIGN KEY (id_productos) REFERENCES proveedor(id_productos),
    FOREIGN KEY (id_tienda) REFERENCES tiendas(id_tienda)
);

--Auditoria para trigger--

CREATE TABLE EMPLEADOS_AUDIT (
    AUDIT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_EMPLEADOS NUMBER,
    OLD_ID_TIENDA NUMBER,
    NEW_ID_TIENDA NUMBER,
    OLD_PUESTO VARCHAR2(100),
    NEW_PUESTO VARCHAR2(100),
    CHANGE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHANGED_BY VARCHAR2(100)
);




-- Vistas
CREATE OR REPLACE VIEW productos_stock AS
SELECT id_producto, nombre, stock_producto
FROM productos
WHERE stock_producto < 10;


CREATE OR REPLACE VIEW ventas_por_tienda AS
SELECT id_tienda, SUM(total) AS total_ventas
FROM ventas
GROUP BY id_tienda;


CREATE OR REPLACE VIEW clientes_frecuentes AS
SELECT c.id_cliente, c.nombre, c.apellido, COUNT(v.id_ventas) AS compras_realizadas
FROM clientes c
JOIN ventas v ON c.id_cliente = v.id_cliente
GROUP BY c.id_cliente, c.nombre, c.apellido
HAVING COUNT(v.id_ventas) > 5;


CREATE OR REPLACE VIEW ventas_por_empleado AS
SELECT 
    id_empleado, 
    SUM(total) AS total_ventas
FROM 
    ventas
GROUP BY 
    id_empleado;

CREATE OR REPLACE VIEW dia_mas_ventas AS
SELECT 
    fecha, 
    SUM(cantidad) AS total_cantidad_ventas,
    SUM(total) AS total_monto_ventas
FROM 
    ventas
GROUP BY 
    fecha
HAVING 
    SUM(cantidad) = (
        SELECT MAX(SUM(cantidad))
        FROM ventas
        GROUP BY fecha
    );

CREATE OR REPLACE VIEW dia_menos_ventas AS
SELECT 
    fecha, 
    SUM(cantidad) AS total_cantidad_ventas,
    SUM(total) AS total_monto_ventas
FROM 
    ventas
GROUP BY 
    fecha
HAVING 
    SUM(cantidad) = (
        SELECT MIN(SUM(cantidad))
        FROM ventas
        GROUP BY fecha
    );

CREATE OR REPLACE VIEW productos_mas_vendidos AS
SELECT 
    p.id_producto,
    p.nombre AS nombre_producto,
    c.nombre AS categoria,
    SUM(v.cantidad) AS cantidad_total_vendida,
    SUM(v.total) AS ingreso_total
FROM productos p
JOIN categorias c ON p.id_categoria = c.id_categoria
JOIN ventas v ON p.id_producto = v.id_producto
GROUP BY p.id_producto, p.nombre, c.nombre
ORDER BY cantidad_total_vendida DESC;


CREATE OR REPLACE VIEW resumen_tiendas AS
SELECT 
    t.id_tienda,
    t.nombre AS nombre_tienda,
    t.direccion AS direccion_tienda,
    t.ciudad AS ciudad_tienda,
    COUNT(DISTINCT e.id_empleados) AS total_empleados,
    COUNT(v.id_ventas) AS total_ventas,
    SUM(v.total) AS ingreso_total
FROM tiendas t
LEFT JOIN empleados e ON t.id_tienda = e.id_tienda
LEFT JOIN ventas v ON t.id_tienda = v.id_tienda
GROUP BY t.id_tienda, t.nombre, t.direccion, t.ciudad
ORDER BY ingreso_total DESC;

CREATE OR REPLACE VIEW productos_mas_vendidos AS
SELECT 
    p.id_producto,
    p.nombre AS nombre_producto,
    c.nombre AS categoria,
    SUM(v.cantidad) AS cantidad_total_vendida,
    SUM(v.total) AS ingreso_total
FROM productos p
JOIN categorias c ON p.id_categoria = c.id_categoria
JOIN ventas v ON p.id_producto = v.id_producto
GROUP BY p.id_producto, p.nombre, c.nombre
ORDER BY cantidad_total_vendida DESC;


-- Funciones
CREATE OR REPLACE FUNCTION calcular_descuento(precio_producto NUMBER, porcentaje_descuento NUMBER)
RETURN NUMBER IS
BEGIN
    RETURN precio_producto - (precio_producto * (porcentaje_descuento / 100));
END;


CREATE OR REPLACE FUNCTION obtener_nombre_cliente(p_id_cliente NUMBER)
RETURN VARCHAR2 IS
    v_nombre VARCHAR2(100);
BEGIN
    SELECT nombre INTO v_nombre
    FROM clientes
    WHERE id_cliente = p_id_cliente;
    RETURN v_nombre;
END;


CREATE OR REPLACE FUNCTION validar_stock(id_producto NUMBER, cantidad NUMBER)
RETURN VARCHAR2 IS
    stock_actual NUMBER;
BEGIN
    SELECT stock_producto INTO stock_actual
    FROM productos
    WHERE id_producto = id_producto;

    IF stock_actual >= cantidad THEN
        RETURN 'Suficiente stock';
    ELSE
        RETURN 'Stock insuficiente';
    END IF;
END;



-- Paquetes
-- Paquete para gestionar productos
CREATE OR REPLACE PACKAGE gestionar_productos AS
    PROCEDURE actualizar_precio(p_id_producto NUMBER, nuevo_precio NUMBER);
    
END gestionar_productos;

CREATE OR REPLACE PACKAGE BODY gestionar_productos AS
    PROCEDURE actualizar_precio(p_id_producto NUMBER, nuevo_precio NUMBER) IS
    BEGIN
        UPDATE productos
        SET precio_producto = nuevo_precio
        WHERE id_producto = p_id_producto;
    END;
END gestionar_productos;

-- Paquete para gestionar clientes
CREATE OR REPLACE PACKAGE gestionar_clientes AS
    FUNCTION obtener_datos_cliente(p_id_cliente NUMBER) RETURN VARCHAR2;
    PROCEDURE actualizar_direccion(p_id_cliente NUMBER, nueva_direccion VARCHAR2);
    CURSOR cur_listar_clientes_frecuentes RETURN clientes%ROWTYPE;
END gestionar_clientes;

CREATE OR REPLACE PACKAGE BODY gestionar_clientes AS
    FUNCTION obtener_datos_cliente(p_id_cliente NUMBER) RETURN VARCHAR2 IS
        v_datos_cliente VARCHAR2(500);
    BEGIN
        SELECT nombre || ' ' || apellido || ' - ' ||
               email || ' - ' || telefono || ' - ' ||
               direccion INTO v_datos_cliente
        FROM clientes
        WHERE id_cliente = p_id_cliente;
        RETURN v_datos_cliente;
    END;

    PROCEDURE actualizar_direccion(p_id_cliente NUMBER, nueva_direccion VARCHAR2) IS
    BEGIN
        UPDATE clientes
        SET direccion = nueva_direccion
        WHERE id_cliente = p_id_cliente;
    END;

    CURSOR cur_listar_clientes_frecuentes IS
        SELECT *
        FROM clientes c
        WHERE c.id_cliente IN (
            SELECT id_cliente
            FROM ventas
            GROUP BY id_cliente
            HAVING COUNT(id_ventas) > 5
        );
END gestionar_clientes;

-- Paquete para gestionar ventas
CREATE OR REPLACE PACKAGE gestionar_ventas AS
    FUNCTION calcular_total_venta(p_id_venta NUMBER) RETURN NUMBER;
    PROCEDURE registrar_venta(
        p_id_cliente NUMBER,
        p_id_empleado NUMBER,
        p_id_producto NUMBER,
        p_id_tienda NUMBER,
        p_cantidad NUMBER
    );
END gestionar_ventas;

CREATE OR REPLACE PACKAGE BODY gestionar_ventas AS
    FUNCTION calcular_total_venta(p_id_venta NUMBER) RETURN NUMBER IS
        v_total NUMBER;
    BEGIN
        SELECT total INTO v_total
        FROM ventas
        WHERE id_ventas = p_id_venta;
        RETURN v_total;
    END;

    PROCEDURE registrar_venta(
        p_id_cliente NUMBER,
        p_id_empleado NUMBER,
        p_id_producto NUMBER,
        p_id_tienda NUMBER,
        p_cantidad NUMBER
    ) IS
        v_precio_producto NUMBER;
        v_total NUMBER;
    BEGIN
        SELECT precio_producto INTO v_precio_producto
        FROM productos
        WHERE id_producto = p_id_producto;

        v_total := v_precio_producto * p_cantidad;

        INSERT INTO ventas (id_cliente, id_empleado, id_producto,
                            id_tienda, fecha, cantidad, total)
                            
        VALUES (p_id_cliente, p_id_empleado, p_id_producto,
                p_id_tienda, SYSDATE, p_cantidad, v_total);

        UPDATE productos
        SET stock_producto = stock_producto - p_cantidad
        WHERE id_producto = p_id_producto;
    END;
END gestionar_ventas;

-- Paquete para gestionar inventarios
CREATE OR REPLACE PACKAGE gestionar_inventarios AS
    FUNCTION verificar_stock(p_id_producto NUMBER, p_id_tienda NUMBER) RETURN NUMBER;
    PROCEDURE actualizar_inventario(p_id_producto NUMBER, p_id_tienda NUMBER, nueva_cantidad NUMBER);
    CURSOR listar_inventarios_bajos RETURN inventarios%ROWTYPE;
END gestionar_inventarios;

CREATE OR REPLACE PACKAGE BODY gestionar_inventarios AS
    FUNCTION verificar_stock(p_id_producto NUMBER, p_id_tienda NUMBER) RETURN NUMBER IS
        v_cantidad NUMBER;
    BEGIN
        SELECT cantidad INTO v_cantidad
        FROM inventarios
        WHERE id_producto = p_id_producto AND id_tienda = p_id_tienda;
        RETURN v_cantidad;
    END;

    PROCEDURE actualizar_inventario(p_id_producto NUMBER, p_id_tienda NUMBER, nueva_cantidad NUMBER) IS
    BEGIN
        UPDATE inventarios
        SET cantidad = nueva_cantidad
        WHERE id_producto = p_id_producto AND id_tienda = p_id_tienda;
    END;

    CURSOR listar_inventarios_bajos RETURN inventarios%ROWTYPE IS
        SELECT *
        FROM inventarios
        WHERE cantidad < 10;
END gestionar_inventarios;

-- Paquete para gestionar empleados
CREATE OR REPLACE PACKAGE gestionar_empleados AS
    FUNCTION obtener_empleado(p_id_empleado NUMBER) RETURN VARCHAR2;
    PROCEDURE asignar_empleado_tienda(p_id_empleado NUMBER, p_id_tienda NUMBER);
    CURSOR listar_empleados_tienda(p_id_tienda NUMBER) RETURN empleados%ROWTYPE;
END gestionar_empleados;

CREATE OR REPLACE PACKAGE BODY gestionar_empleados AS
    FUNCTION obtener_empleado(p_id_empleado NUMBER) RETURN VARCHAR2 IS
        v_empleado VARCHAR2(200);
    BEGIN
        SELECT nombre || ' ' || apellido || ' - ' || puesto INTO v_empleado
        FROM empleados
        WHERE id_empleados = p_id_empleado;
        RETURN v_empleado;
    END;

    PROCEDURE asignar_empleado_tienda(p_id_empleado NUMBER, p_id_tienda NUMBER) IS
    BEGIN
        UPDATE empleados
        SET id_tienda = p_id_tienda
        WHERE id_empleados = p_id_empleado;
    END;

    CURSOR cur_listar_empleados_tienda(p_id_tienda NUMBER) RETURN empleados%ROWTYPE IS
        SELECT *
        FROM empleados
        WHERE id_tienda = p_id_tienda;
END gestionar_empleados;


--Paquete para gestionar proveedores--
CREATE OR REPLACE PACKAGE gestionar_proveedores AS
    FUNCTION obtener_info_proveedor(p_id_proveedor NUMBER) RETURN VARCHAR2;
    PROCEDURE actualizar_telefono_proveedor(p_id_proveedor NUMBER, p_nuevo_telefono VARCHAR2);
    CURSOR listar_proveedores_ciudad(p_ciudad VARCHAR2) RETURN proveedor%ROWTYPE;
END gestionar_proveedores;
/

CREATE OR REPLACE PACKAGE BODY gestionar_proveedores AS
    FUNCTION obtener_info_proveedor(p_id_proveedor NUMBER) RETURN VARCHAR2 IS
        v_info VARCHAR2(200);
    BEGIN
        SELECT nombre || ' - ' || ciudad || ' - ' || telefono 
        INTO v_info FROM proveedor WHERE id_proveedor = p_id_proveedor;
        RETURN v_info;
    END;

    PROCEDURE actualizar_telefono_proveedor(p_id_proveedor NUMBER, p_nuevo_telefono VARCHAR2) IS
    BEGIN
        UPDATE proveedor SET telefono = p_nuevo_telefono WHERE id_proveedor = p_id_proveedor;
    END;

    CURSOR listar_proveedores_ciudad(p_ciudad VARCHAR2) IS
        SELECT * FROM proveedor WHERE ciudad = p_ciudad;
END gestionar_proveedores;
/

--Gestionar pedidos paquete--

CREATE OR REPLACE PACKAGE gestionar_pedidos AS
    FUNCTION obtener_total_pedido(p_id_pedido NUMBER) RETURN NUMBER;
    PROCEDURE registrar_pedido(
        p_id_proveedor NUMBER, p_id_tienda NUMBER, 
        p_fecha DATE, p_total_unidades NUMBER, p_id_producto NUMBER);
    CURSOR listar_pedidos_recientes(p_dias NUMBER) RETURN pedidos%ROWTYPE;
END gestionar_pedidos;
/

CREATE OR REPLACE PACKAGE BODY gestionar_pedidos AS
    FUNCTION obtener_total_pedido(p_id_pedido NUMBER) RETURN NUMBER IS
        v_total NUMBER;
    BEGIN
        SELECT total_unidades INTO v_total FROM pedidos WHERE id_pedido = p_id_pedido;
        RETURN v_total;
    END;

    PROCEDURE registrar_pedido(
        p_id_proveedor NUMBER, p_id_tienda NUMBER, 
        p_fecha DATE, p_total_unidades NUMBER, p_id_producto NUMBER) IS
    BEGIN
        INSERT INTO pedidos (id_proveedor, id_tienda, fecha_pedido, total_unidades, id_productos)
        VALUES (p_id_proveedor, p_id_tienda, p_fecha, p_total_unidades, p_id_producto);
    END;

    CURSOR listar_pedidos_recientes(p_dias NUMBER) IS
        SELECT * FROM pedidos WHERE fecha_pedido > SYSDATE - p_dias;
END gestionar_pedidos;
/

--Reportes Paquete--

CREATE OR REPLACE PACKAGE reportes_generales AS
    PROCEDURE reporte_ventas_tienda(p_id_tienda NUMBER);
    PROCEDURE reporte_stock_bajo;
END reportes_generales;
/

CREATE OR REPLACE PACKAGE BODY reportes_generales AS
    PROCEDURE reporte_ventas_tienda(p_id_tienda NUMBER) IS
        CURSOR ventas_cursor IS
            SELECT fecha, id_producto, cantidad, total 
            FROM ventas WHERE id_tienda = p_id_tienda;
        v_venta ventas%ROWTYPE;
    BEGIN
        OPEN ventas_cursor;
        LOOP
            FETCH ventas_cursor INTO v_venta;
            EXIT WHEN ventas_cursor%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE('Fecha: ' || v_venta.fecha || 
                                 ', Producto: ' || v_venta.id_producto || 
                                 ', Cantidad: ' || v_venta.cantidad || 
                                 ', Total: ' || v_venta.total);
        END LOOP;
        CLOSE ventas_cursor;
    END;

    PROCEDURE reporte_stock_bajo IS
        CURSOR stock_cursor IS
            SELECT nombre, stock_producto 
            FROM productos WHERE stock_producto < 10;
        v_producto productos%ROWTYPE;
    BEGIN
        OPEN stock_cursor;
        LOOP
            FETCH stock_cursor INTO v_producto;
            EXIT WHEN stock_cursor%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE('Producto: ' || v_producto.nombre || 
                                 ', Stock: ' || v_producto.stock_producto);
        END LOOP;
        CLOSE stock_cursor;
    END;
END reportes_generales;
/


--Paquete que se encarga de analizar las ventas--
CREATE OR REPLACE PACKAGE analizar_ventas AS
    FUNCTION ventas_totales_tienda(p_id_tienda NUMBER) RETURN NUMBER;
    FUNCTION top_producto_vendido(p_id_tienda NUMBER) RETURN VARCHAR2;
    CURSOR ventas_por_mes(p_fecha_inicio DATE) RETURN ventas%ROWTYPE;
END analizar_ventas;
/ 

CREATE OR REPLACE PACKAGE BODY analizar_ventas AS
    -- Función para calcular ventas totales por tienda
    FUNCTION ventas_totales_tienda(p_id_tienda NUMBER) RETURN NUMBER IS
        v_total NUMBER := 0;  -- Inicializamos con 0
    BEGIN
        SELECT SUM(total)
        INTO v_total
        FROM ventas
        WHERE id_tienda = p_id_tienda;
        
        -- Utilizamos NVL para garantizar que el valor no sea nulo
        RETURN NVL(v_total, 0);  -- Devuelve 0 si v_total es NULL
    END ventas_totales;

    -- Función para obtener el producto más vendido en una tienda
    FUNCTION top_producto_vendido(p_id_tienda NUMBER) RETURN VARCHAR2 IS
        v_producto VARCHAR2(100);
    BEGIN
        SELECT p.nombre
        INTO v_producto
        FROM productos p
        JOIN ventas v ON p.id_producto = v.id_producto
        WHERE v.id_tienda = p_id_tienda
        GROUP BY p.nombre
        ORDER BY SUM(v.cantidad) DESC
        FETCH FIRST 1 ROWS ONLY;
        RETURN v_producto;
    END top_producto_vendido;

    -- Cursor para listar ventas por mes
    CURSOR ventas_por_mes(p_fecha_inicio DATE) RETURN ventas%ROWTYPE IS
        SELECT *
        FROM ventas
        WHERE fecha >= p_fecha_inicio;

END analizar_ventas;




CREATE OR REPLACE PACKAGE gestionar_categorias AS
    FUNCTION obtener_categoria(p_id_categoria NUMBER) RETURN VARCHAR2;
    PROCEDURE agregar_categoria(p_nombre VARCHAR2);
    CURSOR listar_categorias RETURN categorias%ROWTYPE;
END gestionar_categorias;
/

--Paquete que nos ayuda a gestionar las categorias--

CREATE OR REPLACE PACKAGE BODY gestionar_categorias AS
    FUNCTION obtener_categoria(p_id_categoria NUMBER) RETURN VARCHAR2 IS
        v_categoria VARCHAR2(100);
    BEGIN
        SELECT nombre INTO v_categoria FROM categorias WHERE id_categoria = p_id_categoria;
        RETURN v_categoria;
    END;

    PROCEDURE agregar_categoria(p_nombre VARCHAR2) IS
    BEGIN
        INSERT INTO categorias (nombre) VALUES (p_nombre);
    END;

    CURSOR listar_categorias IS
        SELECT * FROM categorias;
END gestionar_categorias;
/



-- Trigger
CREATE OR REPLACE TRIGGER actualizar_inventario
AFTER INSERT ON ventas
FOR EACH ROW
BEGIN
    UPDATE productos
    SET stock_producto = stock_producto - :NEW.cantidad
    WHERE id_producto = :NEW.id_producto;
END;
--Permite ver si el trriger esta habilitado si esta habilitado no permite insertar en la tabla de ventas--
SELECT trigger_name, status
FROM user_triggers
WHERE trigger_name = 'ACTUALIZAR_INVENTARIO';
ALTER TRIGGER C##PROYECTOBD.ACTUALIZAR_INVENTARIO DISABLE;



CREATE OR REPLACE TRIGGER validar_stock
BEFORE UPDATE OF stock_producto ON productos
FOR EACH ROW
BEGIN
    IF :NEW.stock_producto < 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'El stock no puede ser negativo');
    END IF;
END;

--Este trigger funciona para ver cambios en custion de auditoria entre el puesto y el id_tienda de los empleados
CREATE OR REPLACE TRIGGER TRG_EMPLEADOS_AUDIT
BEFORE UPDATE OF PUESTO, ID_TIENDA ON EMPLEADOS
FOR EACH ROW
BEGIN
    -- Insertar los datos en la tabla de auditoría
    INSERT INTO EMPLEADOS_AUDIT (
        ID_EMPLEADOS, 
        OLD_ID_TIENDA, 
        NEW_ID_TIENDA, 
        OLD_PUESTO, 
        NEW_PUESTO, 
        CHANGED_BY
    )
    VALUES (
        :OLD.ID_EMPLEADOS, 
        :OLD.ID_TIENDA, 
        :NEW.ID_TIENDA, 
        :OLD.PUESTO, 
        :NEW.PUESTO, 
        USER
    );
END;
/

-- Actualizar un registro en EMPLEADOS
UPDATE EMPLEADOS
SET ID_TIENDA = 2, 
    PUESTO = 'Gerente'
WHERE ID_EMPLEADOS = 101;

-- Verificar los datos en la tabla de auditoría
SELECT * FROM EMPLEADOS_AUDIT;


-- Cursores
DECLARE
    CURSOR c_stock_bajo IS
        SELECT id_producto, nombre, stock_producto
        FROM productos
        WHERE stock_producto < 10;
    v_id_producto productos.id_producto%TYPE;
    v_nombre productos.nombre%TYPE;
    v_stock productos.stock_producto%TYPE;
BEGIN
    OPEN c_stock_bajo;
    LOOP
        FETCH c_stock_bajo INTO v_id_producto, v_nombre, v_stock;
        EXIT WHEN c_stock_bajo%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('Producto: ' || v_nombre || ' - Stock: ' || v_stock);
    END LOOP;
    CLOSE c_stock_bajo;
END;



DECLARE
    CURSOR c_ventas_cliente IS
        SELECT c.nombre, SUM(v.total) AS total_compras
        FROM clientes c
        JOIN ventas v ON c.id_cliente = v.id_cliente
        GROUP BY c.nombre;
    v_nombre clientes.nombre%TYPE;
    v_total NUMBER;
BEGIN
    OPEN c_ventas_cliente;
    LOOP
        FETCH c_ventas_cliente INTO v_nombre, v_total;
        EXIT WHEN c_ventas_cliente%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('Cliente: ' || v_nombre || ' - Total Compras: ' || v_total);
    END LOOP;
    CLOSE c_ventas_cliente;
END;

--Procedimientos Almacenados

CREATE OR REPLACE PROCEDURE agregar_tienda(
    p_nombre IN VARCHAR2,
    p_direccion IN VARCHAR2,
    p_ciudad IN VARCHAR2
) AS
BEGIN
    INSERT INTO tiendas (nombre, direccion, ciudad)
    VALUES (p_nombre, p_direccion, p_ciudad);
END;
/

CREATE OR REPLACE PROCEDURE agregar_empleado(
    p_id_tienda IN NUMBER,
    p_nombre IN VARCHAR2,
    p_apellido IN VARCHAR2,
    p_puesto IN VARCHAR2
) AS
BEGIN
    INSERT INTO empleados (id_tienda, nombre, apellido, puesto)
    VALUES (p_id_tienda, p_nombre, p_apellido, p_puesto);
END;
/

CREATE OR REPLACE PROCEDURE agregar_cliente(
    p_nombre IN VARCHAR2,
    p_apellido IN VARCHAR2,
    p_email IN VARCHAR2,
    p_telefono IN VARCHAR2,
    p_direccion IN VARCHAR2
) AS
BEGIN
    INSERT INTO clientes (nombre, apellido, email, telefono, direccion)
    VALUES (p_nombre, p_apellido, p_email, p_telefono, p_direccion);
END;
/

CREATE OR REPLACE PROCEDURE agregar_categoria(
    p_nombre IN VARCHAR2
) AS
BEGIN
    INSERT INTO categorias (nombre)
    VALUES (p_nombre);
END;
/

CREATE OR REPLACE PROCEDURE agregar_producto(
    p_id_categoria IN NUMBER,
    p_nombre IN VARCHAR2,
    p_precio_producto IN NUMBER,
    p_stock_producto IN NUMBER,
    p_descripcion IN VARCHAR2
) AS
BEGIN
    INSERT INTO productos (id_categoria, nombre, precio_producto, stock_producto, descripcion)
    VALUES (p_id_categoria, p_nombre, p_precio_producto, p_stock_producto, p_descripcion);
END;
/

CREATE OR REPLACE PROCEDURE agregar_inventario(
    p_id_tienda IN NUMBER,
    p_total_productos IN NUMBER
) AS
BEGIN
    INSERT INTO inventarios (id_tienda, total_productos)
    VALUES (p_id_tienda, p_total_productos);
END;
/

CREATE OR REPLACE PROCEDURE agregar_venta(
    p_id_cliente IN NUMBER,
    p_id_empleado IN NUMBER,
    p_id_producto IN NUMBER,
    p_id_tienda IN NUMBER,
    p_fecha IN DATE,
    p_cantidad IN NUMBER,
    p_total IN NUMBER
) AS
BEGIN
    INSERT INTO ventas (id_cliente, id_empleado, id_producto, id_tienda, fecha, cantidad, total)
    VALUES (p_id_cliente, p_id_empleado, p_id_producto, p_id_tienda, p_fecha, p_cantidad, p_total);
END;
/

CREATE OR REPLACE PROCEDURE agregar_proveedor(
    p_nombre IN VARCHAR2,
    p_descripcion IN VARCHAR2,
    p_ciudad IN VARCHAR2,
    p_telefono IN VARCHAR2
) AS
BEGIN
    INSERT INTO proveedor (nombre, descripcion, ciudad, telefono)
    VALUES (p_nombre, p_descripcion, p_ciudad, p_telefono);
END;
/

CREATE OR REPLACE PROCEDURE agregar_pedido(
    p_id_proveedor IN NUMBER,
    p_fecha_pedido IN DATE,
    p_total_unidades IN NUMBER,
    p_id_productos IN NUMBER
) AS
BEGIN
    INSERT INTO pedidos (id_proveedor, fecha_pedido, total_unidades, id_productos)
    VALUES (p_id_proveedor, p_fecha_pedido, p_total_unidades, p_id_productos);
END;
/

CREATE OR REPLACE PROCEDURE modificar_tienda(
    p_id_tienda IN NUMBER,
    p_nombre IN VARCHAR2,
    p_direccion IN VARCHAR2,
    p_ciudad IN VARCHAR2
) AS
BEGIN
    UPDATE tiendas
    SET nombre = p_nombre,
        direccion = p_direccion,
        ciudad = p_ciudad
    WHERE id_tienda = p_id_tienda;
END;
/

CREATE OR REPLACE PROCEDURE modificar_empleado(
    p_id_empleado IN NUMBER,
    p_id_tienda IN NUMBER,
    p_nombre IN VARCHAR2,
    p_apellido IN VARCHAR2,
    p_puesto IN VARCHAR2
) AS
BEGIN
    UPDATE empleados
    SET id_tienda = p_id_tienda,
        nombre = p_nombre,
        apellido = p_apellido,
        puesto = p_puesto
    WHERE id_empleados = p_id_empleado;
END;
/

CREATE OR REPLACE PROCEDURE modificar_cliente(
    p_id_cliente IN NUMBER,
    p_nombre IN VARCHAR2,
    p_apellido IN VARCHAR2,
    p_email IN VARCHAR2,
    p_telefono IN VARCHAR2,
    p_direccion IN VARCHAR2
) AS
BEGIN
    UPDATE clientes
    SET nombre = p_nombre,
        apellido = p_apellido,
        email = p_email,
        telefono = p_telefono,
        direccion = p_direccion
    WHERE id_cliente = p_id_cliente;
END;
/

CREATE OR REPLACE PROCEDURE modificar_producto(
    p_id_producto IN NUMBER,
    p_id_categoria IN NUMBER,
    p_nombre IN VARCHAR2,
    p_precio_producto IN NUMBER,
    p_stock_producto IN NUMBER,
    p_descripcion IN VARCHAR2
) AS
BEGIN
    UPDATE productos
    SET id_categoria = p_id_categoria,
        nombre = p_nombre,
        precio_producto = p_precio_producto,
        stock_producto = p_stock_producto,
        descripcion = p_descripcion
    WHERE id_producto = p_id_producto;
END;
/

CREATE OR REPLACE PROCEDURE modificar_inventario(
    p_id_inventario IN NUMBER,
    p_id_tienda IN NUMBER,
    p_total_productos IN NUMBER
) AS
BEGIN
    UPDATE inventarios
    SET id_tienda = p_id_tienda,
        total_productos = p_total_productos
    WHERE id_inventario = p_id_inventario;
END;
/

CREATE OR REPLACE PROCEDURE modificar_proveedor(
    p_id_proveedor IN NUMBER,
    p_nombre IN VARCHAR2,
    p_descripcion IN VARCHAR2,
    p_ciudad IN VARCHAR2,
    p_telefono IN VARCHAR2
) AS
BEGIN
    UPDATE proveedor
    SET nombre = p_nombre,
        descripcion = p_descripcion,
        ciudad = p_ciudad,
        telefono = p_telefono
    WHERE id_proveedor = p_id_proveedor;
END;
/

CREATE OR REPLACE PROCEDURE modificar_pedido(
    p_id_pedido IN NUMBER,
    p_id_proveedor IN NUMBER,
    p_fecha_pedido IN DATE,
    p_total_unidades IN NUMBER,
    p_id_productos IN NUMBER
) AS
BEGIN
    UPDATE pedidos
    SET id_proveedor = p_id_proveedor,
        fecha_pedido = p_fecha_pedido,
        total_unidades = p_total_unidades,
        id_productos = p_id_productos
    WHERE id_pedido = p_id_pedido;
END;
/

CREATE OR REPLACE PROCEDURE modificar_categoria (
    p_id_categoria IN NUMBER,
    p_nombre IN VARCHAR2
) AS
BEGIN
    -- Modificar el nombre de la categoría
    UPDATE categorias
    SET nombre = p_nombre
    WHERE id_categoria = p_id_categoria;

    -- Confirmar los cambios
    COMMIT;
END;
/


CREATE OR REPLACE PROCEDURE actualizar_ventas (
    p_id_categoria IN NUMBER,
    p_incremento IN NUMBER
) AS
BEGIN
   
    UPDATE ventas
    SET total = total + (total * p_incremento / 100)
    WHERE id_producto IN (
        SELECT id_producto 
        FROM productos 
        WHERE id_categoria = p_id_categoria
    );

  
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE actualizar_empleado (
    p_id_empleados IN NUMBER,
    p_id_tienda IN NUMBER,
    p_nombre IN VARCHAR2,
    p_apellido IN VARCHAR2,
    p_puesto IN VARCHAR2
) AS
BEGIN
   
    UPDATE empleados
    SET 
        id_tienda = p_id_tienda,
        nombre = p_nombre,
        apellido = p_apellido,
        puesto = p_puesto
    WHERE id_empleados = p_id_empleados;

    
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE actualizar_cliente (
    p_id_cliente IN NUMBER,
    p_nombre IN VARCHAR2,
    p_apellido IN VARCHAR2,
    p_email IN VARCHAR2,
    p_telefono IN VARCHAR2,
    p_direccion IN VARCHAR2
) AS
BEGIN
 
    UPDATE clientes
    SET 
        nombre = p_nombre,
        apellido = p_apellido,
        email = p_email,
        telefono = p_telefono,
        direccion = p_direccion
    WHERE id_cliente = p_id_cliente;

  
    COMMIT;
END;
/

--Inserts

INSERT INTO tiendas (nombre, direccion, ciudad) 
VALUES ('Tienda Centro', 'Calle Blancos, Zona 1', 'Ciudad A');

INSERT INTO tiendas (nombre, direccion, ciudad) 
VALUES ('Tienda Norte', 'Avenida 4, Zona 3', 'Ciudad B');

INSERT INTO tiendas (nombre, direccion, ciudad) 
VALUES ('Tienda Sur', 'Calle 8, Zona 5', 'Ciudad C');

INSERT INTO empleados (id_tienda, nombre, apellido, puesto) 
VALUES (1, 'Carlos', 'López', 'Vendedor');

INSERT INTO empleados (id_tienda, nombre, apellido, puesto) 
VALUES (2, 'Ana', 'Martínez', 'Gerente');

INSERT INTO empleados (id_tienda, nombre, apellido, puesto) 
VALUES (3, 'Luis', 'Ramírez', 'Cajero');


INSERT INTO clientes (nombre, apellido, email, telefono, direccion) 
VALUES ('Juan', 'Pérez', 'juanez@gmail.com', '888888876', 'Calle Falles ');

INSERT INTO clientes (nombre, apellido, email, telefono, direccion) 
VALUES ('María', 'González', 'mariag@gmail.com', '888888875', 'Avenida Segunda ');

INSERT INTO clientes (nombre, apellido, email, telefono, direccion) 
VALUES ('Elena', 'Hernández', 'elenahernandezgemail.com', '588888886', 'Calle Blancos ');

INSERT INTO categorias (nombre) 
VALUES ('Electrónica');

INSERT INTO categorias (nombre) 
VALUES ('Hogar');

INSERT INTO categorias (nombre) 
VALUES ('Ropa');

SELECT FROM * categorias;

INSERT INTO productos (id_categoria, id_proveedor, nombre, precio_producto, stock_producto, descripcion) 
VALUES (1, 1, 'Celular', 500000, 20, 'Celular con cámara de alta resolución');

INSERT INTO productos (id_categoria, id_proveedor, nombre, precio_producto, stock_producto, descripcion) 
VALUES (22, 2, 'Sofá', 600000, 20, 'Sofá de 3 plazas, cómodo y elegante');

INSERT INTO productos (id_categoria, id_proveedor, nombre, precio_producto, stock_producto, descripcion) 
VALUES (23, 3, 'Chaqueta de invierno', 20000, 30, 'Chaqueta de abrigo para clima frío');

INSERT INTO inventarios (id_tienda, total_productos) 
VALUES (1, 500);

INSERT INTO inventarios (id_tienda, total_productos) 
VALUES (2, 300);

INSERT INTO inventarios (id_tienda, total_productos) 
VALUES (3, 400);

INSERT INTO ventas (id_cliente, id_empleado, id_producto, id_tienda, fecha, cantidad, total) 
VALUES (1, 1, 27, 1, TO_DATE('2024-01-10', 'YYYY-MM-DD'), 1, 500000);

INSERT INTO ventas (id_cliente, id_empleado, id_producto, id_tienda, fecha, cantidad, total) 
VALUES (2, 2, 28, 2, TO_DATE('2024-01-15', 'YYYY-MM-DD'), 1, 600000);

INSERT INTO ventas (id_cliente, id_empleado, id_producto, id_tienda, fecha, cantidad, total) 
VALUES (3, 3, 29, 3, TO_DATE('2024-01-20', 'YYYY-MM-DD'), 2, 40000);

INSERT INTO proveedor (nombre, descripcion, ciudad, telefono) 
VALUES ('Proveedor A', 'Proveedor de productos electrónicos', 'Ciudad A', '5551239876');

INSERT INTO proveedor (nombre, descripcion, ciudad, telefono) 
VALUES ('Proveedor B', 'Proveedor de muebles y decoración', 'Ciudad B', '5556543210');

INSERT INTO proveedor (nombre, descripcion, ciudad, telefono) 
VALUES ('Proveedor C', 'Proveedor de ropa y calzado', 'Ciudad C', '5557896543');

INSERT INTO pedidos (id_proveedor, id_tienda, fecha_pedido, total_unidades, id_productos) 
VALUES (1, 1, TO_DATE('2024-01-10', 'YYYY-MM-DD'), 20, 1);

INSERT INTO pedidos (id_proveedor, id_tienda, fecha_pedido, total_unidades, id_productos) 
VALUES (2, 2, TO_DATE('2024-01-15', 'YYYY-MM-DD'), 15, 2);

INSERT INTO pedidos (id_proveedor, id_tienda, fecha_pedido, total_unidades, id_productos) 
VALUES (3, 3, TO_DATE('2024-01-20', 'YYYY-MM-DD'), 30, 3);


SELECT * FROM categorias;
SELECT * FROM proveedor;
SELECT * FROM empleados;
SELECT * FROM clientes;
SELECT * FROM tiendas;
SELECT * FROM productos;
SELECT * FROM inventarios;
SELECT * FROM ventas;
SELECT * FROM pedidos;

SELECT * FROM productos WHERE id_producto = 28;

SELECT * FROM clientes WHERE id_cliente = 2;
SELECT * FROM empleados WHERE id_empleados = 2;
SELECT * FROM tiendas WHERE id_tienda = 2;

